# Generated by Django 5.2.7 on 2025-11-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sku", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("qty", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "AVAILABLE"),
                            ("PENDING", "PENDING"),
                            ("OUT", "OUT"),
                        ],
                        default="AVAILABLE",
                        max_length=16,
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
