# Generated by Django 5.2.7 on 2025-11-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "Disponible"), ("PENDING", "En espera"), ("OUT", "Agotado")],
                default="AVAILABLE",
                max_length=16,
            ),
        ),
    ]
