# Generated by Django 5.2.7 on 2025-11-03 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_fix_price_column"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("delta", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("ADJUSTMENT", "Ajuste manual"),
                            ("DAMAGE", "Merma/daño"),
                            ("RETURN", "Devolución"),
                            ("COUNT", "Diferencia inventario"),
                        ],
                        default="ADJUSTMENT",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.product",
                    ),
                ),
            ],
        ),
    ]
